### ISSUE TITLE
Details about the dataset

### ISSUE THREAD

**Issue by monjurulkarim** [UtopAIBuilder/Grad-CAM-for-video-and-regression-task#1]
Hi, Thanks for this nice repository.
Could you please let me know a little more details of the dataset structures? I mean how the dataset folders look like, what are the annotations, and so on?
Besides, could you please tell me what I have to do if I want to implement your code for different datasets with different number of classes.

Thanks in advance. Looking forward to your reply.

**Comment by UtopAIBuilder** [comment]
I have updated the readme, hope that helps
